name: testing 
on:
 push:
  branches: 
  - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: test with own writing
     run: echo ${{github.run_number}}
 deploy:
  needs: build
  runs-on: windows-latest
  steps:
   - name: test with own writing
     run: echo $(github.run_number)
