name: testing 
on:
 push:
  branches: 
  - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: test with own writing
     run: echo ${{github.run_number}}
   - name: oc-login
     run: ./oc
 deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: test with own writing
     run: echo ${{github.run_number}}
